/* Zenu unified schema — auto-generated from "Zenu Documentation.xlsx". Do not hand-edit. */
window.ZENU_FIELDS = [
  {"name": "contact_identifier", "type": "text", "group": "contact", "desc": "A unique identifier for the contact"},
  {"name": "zenu_contact_id", "type": "integer", "group": "contact", "desc": "An existing Zenu contact ID within your office"},
  {"name": "contact_title", "type": "text", "group": "contact", "desc": "A contact's title", "accepted": ["Mr", "Mrs", "Miss", "Ms"]},
  {"name": "contact_first_name", "type": "text", "group": "contact", "desc": "A contact's first name. Required if a contact_identifier is specified"},
  {"name": "contact_surname", "type": "text", "group": "contact", "desc": "A contact's surname. Required if a contact_identifier is specified"},
  {"name": "contact_is_company", "type": "true/false", "group": "contact", "desc": "A flag to indicate if this contact is a company. If left empty, the default value is 'No'", "accepted": ["True", "False"]},
  {"name": "contact_company_name", "type": "text", "group": "contact", "desc": "A company's name"},
  {"name": "contact_name_on_letters", "type": "text", "group": "contact", "desc": "The name that is to be used on the cover of a letter"},
  {"name": "contact_legal_name", "type": "text", "group": "contact", "desc": "The contact's legal name"},
  {"name": "contact_company_position", "type": "text", "group": "contact", "desc": "The contact's position/role in the company"},
  {"name": "contact_type", "type": "text", "group": "contact", "desc": "High level contact categorisation. Include multiple categories by separating them with a comma"},
  {"name": "contact_tags", "type": "text", "group": "contact", "desc": "Low level tagging. Include multiple tags by separating them with a comma"},
  {"name": "contact_subscriptions", "type": "text", "group": "contact", "desc": "Marketing subscriptions. Include multiple subscription ids by separating them with a comma"},
  {"name": "contact_mailing_address_line1", "type": "text", "group": "contact", "desc": "The first line of the contact's mailing address"},
  {"name": "contact_mailing_address_line2", "type": "text", "group": "contact", "desc": "The second line of the contact's mailing address (usually only used if Address Line 1 is in a building, apartment or named estate)"},
  {"name": "contact_mailing_address_suburb", "type": "text", "group": "contact", "desc": "The name of the suburb for the contact's mailing address"},
  {"name": "contact_mailing_address_town_city", "type": "text", "group": "contact", "desc": "The name of the town/city for the contact's mailing address"},
  {"name": "contact_mailing_address_state", "type": "text", "group": "contact", "desc": "The name of the suburb for the contact's mailing address"},
  {"name": "contact_mailing_address_country", "type": "text", "group": "contact", "desc": "The name of the country for the contact's mailing address"},
  {"name": "contact_mailing_address_postcode", "type": "integer", "group": "contact", "desc": "The name of the postcode for the contact's mailing address"},
  {"name": "contact_email_address", "type": "text", "group": "contact", "desc": "The contact's email address. NB: Only one email address per contact"},
  {"name": "contact_mobile", "type": "text", "group": "contact", "desc": "The contact's mobile"},
  {"name": "contact_phone_work", "type": "text", "group": "contact", "desc": "The contact's work phone number"},
  {"name": "contact_phone_home", "type": "text", "group": "contact", "desc": "The contact's home phone number"},
  {"name": "contact_fax", "type": "text", "group": "contact", "desc": "The contact's fax number"},
  {"name": "contact_allow_contact_via_text", "type": "true/false", "group": "contact", "desc": "Are you allowed to contact this person via text?", "accepted": ["True", "False"]},
  {"name": "contact_allow_contact_via_email", "type": "true/false", "group": "contact", "desc": "Are you allowed to contact this person via email?", "accepted": ["True", "False"]},
  {"name": "contact_allow_contact_via_letter", "type": "true/false", "group": "contact", "desc": "Are you allowed to contact this person via mail?", "accepted": ["True", "False"]},
  {"name": "contact_allow_contact_via_phone", "type": "true/false", "group": "contact", "desc": "Are you allowed to contact this person via phone?", "accepted": ["True", "False"]},
  {"name": "contact_unsubscribe_from_marketing", "type": "true/false", "group": "contact", "desc": "Has this contact unsubscribed from email marketing?", "accepted": ["True", "False"]},
  {"name": "contact_childrens_names", "type": "text", "group": "contact", "desc": "Childrens names"},
  {"name": "contact_enquiry_source", "type": "text", "group": "contact", "desc": "The lead source of the enquiry"},
  {"name": "contact_rating", "type": "integer", "group": "contact", "desc": "The rating of a contact", "accepted": ["Hot", "Warm", "Cold"]},
  {"name": "contact_partner_identifier", "type": "text", "group": "contact", "desc": "If you are linking this contact to a partner, enter the partner's ID"},
  {"name": "contact_partnership_id", "type": "text", "group": "contact", "desc": "ID to indicate that anybody sharing this value has a relationship with each other"},
  {"name": "contact_partnership_type", "type": "text", "group": "contact", "desc": "Relationship to the contact listed in contact_partnership_id", "accepted": ["Aunt", "Brother", "Business Partner", "Co-Owner", "Colleague", "Cousin", "Daughter", "Daughter-In-Law", "De Facto", "Ex-partner"]},
  {"name": "contact_last_contact_date", "type": "date", "group": "contact", "desc": "The date/time that the contact was last contacted"},
  {"name": "contact_date_created", "type": "date", "group": "contact", "desc": "The date/time that the contact was created"},
  {"name": "contact_date_modified", "type": "date", "group": "contact", "desc": "The date/time that the contact was modified"},
  {"name": "contact_criteria_sale_method", "type": "text", "group": "contact", "desc": "Criteria type (Sale/Lease)", "accepted": ["Sale", "Lease"]},
  {"name": "contact_criteria_category", "type": "text", "group": "contact", "desc": "Criteria category (Residential/Commercial/Business/Rural)", "accepted": ["Residential", "Commercial", "Business", "Rural"]},
  {"name": "contact_criteria_property_type", "type": "text", "group": "contact", "desc": "Criteria property type", "accepted": ["AcreageSemi-rural", "Alpine", "Apartment", "BlockOfUnits", "DuplexSemi-detached", "Flat", "House", "Other", "Retirement", "ServicedApartment"]},
  {"name": "contact_criteria_title_type", "type": "text", "group": "contact", "desc": "Criteria title type", "accepted": ["Torrens", "Limited Torrens", "Strata", "Leasehold", "Company", "Community", "Retirement", "Company Share", "Stratum in Freehold", "Stratum in Leasehold"]},
  {"name": "contact_criteria_price_from", "type": "integer", "group": "contact", "desc": "Criteria price (min)", "accepted": ["50000", "100000", "125000", "150000", "175000", "200000", "225000", "250000", "275000", "300000"]},
  {"name": "contact_criteria_price_to", "type": "integer", "group": "contact", "desc": "Criteria price (max)", "accepted": ["50000", "100000", "125000", "150000", "175000", "200000", "225000", "250000", "275000", "300000"]},
  {"name": "contact_criteria_bedrooms", "type": "integer", "group": "contact", "desc": "The contact's criteria for the number of bedrooms they require"},
  {"name": "contact_criteria_bathrooms", "type": "integer", "group": "contact", "desc": "The contact's criteria for the number of bathrooms they require"},
  {"name": "contact_criteria_carspaces", "type": "integer", "group": "contact", "desc": "The contact's criteria for the number of carspaces they require"},
  {"name": "contact_criteria_land_from", "type": "integer", "group": "contact", "desc": "Land size (min)"},
  {"name": "contact_criteria_land_to", "type": "integer", "group": "contact", "desc": "Land size (max)"},
  {"name": "contact_criteria_land_unit", "type": "text", "group": "contact", "desc": "Land size unit of measure", "accepted": ["sqm", "acre", "hectare"]},
  {"name": "contact_criteria_living_area_from", "type": "integer", "group": "contact", "desc": "Internal size (min)"},
  {"name": "contact_criteria_living_area_to", "type": "integer", "group": "contact", "desc": "Internal size (max)"},
  {"name": "contact_criteria_living_area_unit", "type": "text", "group": "contact", "desc": "Internal size unit of measure", "accepted": ["sqm", "sq"]},
  {"name": "contact_criteria_suburbs", "type": "text", "group": "contact", "desc": "The contact's criteria for the suburbs in which they are looking for properties"},
  {"name": "contact_team_member_1", "type": "text", "group": "contact", "desc": "The primary agent of this contact. Can be either the team member's name their Zenu ID"},
  {"name": "contact_team_member_2", "type": "text", "group": "contact", "desc": "The secondary agent to this contact. Can be either the team member's name their Zenu ID"},
  {"name": "contact_team_member_3", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_4", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_5", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_6", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_7", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_8", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_9", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_10", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_11", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_12", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_13", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_14", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_team_member_15", "type": "text", "group": "contact", "desc": "An additional agent to this contact. Can be either the team member's name or their Zenu ID"},
  {"name": "contact_sale_type", "type": "text", "group": "contact", "desc": "The type of property transaction between this contact and property", "accepted": ["seller", "purchaser"]},
  {"name": "zenu_solicitor_id", "type": "integer", "group": "contact", "desc": "An existing Zenu solicitor contact ID within your office that will be assigned to the transaction between the contact and property"},
  {"name": "zenu_company_id", "type": "integer", "group": "contact", "desc": "An existing Zenu company contact ID within your office that will be associated with the contact"},
  {"name": "contact_notes", "type": "text", "group": "contact", "desc": "Notes regarding the contact"},
  {"name": "contact_note_created_date", "type": "date", "group": "contact", "desc": "When the notes were created"},
  {"name": "contact_note_team_member", "type": "text", "group": "contact", "desc": "The creator of the contact note. Is can be either the team member's name their Zenu ID"},
  {"name": "property_identifier", "type": "text", "group": "property", "desc": "A unique identifier for the property"},
  {"name": "zenu_property_id", "type": "integer", "group": "property", "desc": "An existing Zenu property ID within your office"},
  {"name": "property_unit_number", "type": "text", "group": "property", "desc": "The unit number of the property address (if applicable)"},
  {"name": "property_street_number", "type": "text", "group": "property", "desc": "The street number of the property address"},
  {"name": "property_street_name", "type": "text", "group": "property", "desc": "The street name of the property address"},
  {"name": "property_suburb", "type": "text", "group": "property", "desc": "The suburb of the property address"},
  {"name": "property_postcode", "type": "integer", "group": "property", "desc": "The postcode of the property address"},
  {"name": "property_state", "type": "text", "group": "property", "desc": "The state of the property address"},
  {"name": "property_country", "type": "text", "group": "property", "desc": "The country of the property address"},
  {"name": "property_full_address", "type": "text", "group": "property", "desc": "The full address of the property"},
  {"name": "property_building_name", "type": "text", "group": "property", "desc": "Building Name"},
  {"name": "property_sale_method", "type": "text", "group": "property", "desc": "Sale/Lease", "accepted": ["sale", "auction", "lease", "both"]},
  {"name": "property_category", "type": "text", "group": "property", "desc": "Residential/Commercial", "accepted": ["Business", "Commercial", "Residential", "Rural"]},
  {"name": "property_type", "type": "text", "group": "property", "desc": "Type (House/Unit etc)", "accepted": ["AcreageSemi-rural", "Alpine", "Apartment", "BlockOfUnits", "DuplexSemi-detached", "Flat", "Hotel/Leisure", "House", "Industrial/Warehouse", "Land/Development"]},
  {"name": "property_bedrooms", "type": "integer", "group": "property", "desc": "Number of bedrooms"},
  {"name": "property_bathrooms", "type": "integer", "group": "property", "desc": "Number of bathrooms"},
  {"name": "property_toilets", "type": "integer", "group": "property", "desc": "Number of toilets"},
  {"name": "property_total_rooms", "type": "integer", "group": "property", "desc": "Total Rooms"},
  {"name": "property_garages", "type": "integer", "group": "property", "desc": "Number of garage spaces"},
  {"name": "property_carports", "type": "integer", "group": "property", "desc": "Number of carport spaces"},
  {"name": "property_open_parking_spaces", "type": "integer", "group": "property", "desc": "Number of open parking spaces"},
  {"name": "property_living_area_m2", "type": "integer", "group": "property", "desc": "Living Area (m2)"},
  {"name": "property_land_size_m2", "type": "integer", "group": "property", "desc": "Land size"},
  {"name": "listing_land_size_system", "type": "text", "group": "property", "desc": "Land size unit of measurement. Defaults to sqm if not provided", "accepted": ["sqm", "acre", "hectare", "square"]},
  {"name": "property_modified_date", "type": "date", "group": "property", "desc": "The date the property was last modified"},
  {"name": "property_appraisal_date", "type": "date", "group": "property", "desc": "The date the property was appraised"},
  {"name": "property_timeline_status", "type": "text", "group": "property", "desc": "Current status of this prospect/appraisal", "accepted": ["Prospect", "Prospect for Sale", "Prospect for Lease", "Prospect not on market", "Appraisal", "Settled"]},
  {"name": "property_team_member_1", "type": "text", "group": "property", "desc": "The primary agent for the property. Can be either the team member's name or their Zenu ID"},
  {"name": "property_team_member_2", "type": "text", "group": "property", "desc": "The secondary agent for the property. Can be either the team member's name or their Zenu ID"},
  {"name": "property_team_member_3", "type": "text", "group": "property", "desc": "An additional agent for the property. Can be either the team member's name or their Zenu ID"},
  {"name": "property_team_member_4", "type": "text", "group": "property", "desc": "An additional agent for the property. Can be either the team member's name or their Zenu ID"},
  {"name": "property_is_occupied_by_owner", "type": "true/false", "group": "property", "desc": "Is the property ccurrently occupied by the owner", "accepted": ["True", "False"]},
  {"name": "property_appraisal_source", "type": "text", "group": "property", "desc": "The lead source for the appraisal"},
  {"name": "property_is_selling_within_7_days", "type": "true/false", "group": "property", "desc": "Is the property selling within the next seven days?", "accepted": ["True", "False"]},
  {"name": "property_search_price", "type": "integer", "group": "property", "desc": "The search price for the property"},
  {"name": "property_vendor_price", "type": "integer", "group": "property", "desc": "The vendor's asking price"},
  {"name": "property_estimated_commission", "type": "integer", "group": "property", "desc": "Estimated commission upon selling the property (%)"},
  {"name": "property_pipeline_rating", "type": "text", "group": "property", "desc": "Pipeline rating for the property", "accepted": ["A", "B", "C", "D"]},
  {"name": "property_contract_date", "type": "date", "group": "property", "desc": "Contract Date for sold properties"},
  {"name": "property_unconditional_date", "type": "date", "group": "property", "desc": "Sold/unconditional date for sold properties"},
  {"name": "property_settlement_date", "type": "date", "group": "property", "desc": "Settlement date for sold properties"},
  {"name": "property_sold_price", "type": "integer", "group": "property", "desc": "Sold price of a property"},
  {"name": "property_sale_team_member", "type": "text", "group": "property", "desc": "The selling agent of the sold property. Can be either the team member's name their Zenu ID"},
  {"name": "property_sale_team_member_role", "type": "text", "group": "property", "desc": "The role of the selling agents (Lister/Manager/Seller)", "accepted": ["Lister", "Manager", "Seller"]},
  {"name": "property_sale_team_member_recognition_percentage", "type": "integer", "group": "property", "desc": "The percentage of the commission that is given to the sales team members"},
  {"name": "property_sale_team_member_recognition_amount", "type": "integer", "group": "property", "desc": "The dollar value of the commission that is given to the sales team members"},
  {"name": "property_sale_gross_commission", "type": "integer", "group": "property", "desc": "Gross commission for the property sale"},
  {"name": "property_year_built", "type": "integer", "group": "property", "desc": "The year that the property construction was completed"},
  {"name": "property_council_name", "type": "text", "group": "property", "desc": "The name of the council area that the property resides in"},
  {"name": "property_council_zoning", "type": "text", "group": "property", "desc": "Which council zoning the property resides in"},
  {"name": "property_lot_number", "type": "text", "group": "property", "desc": "The lot number used for subdivision"},
  {"name": "property_title_number", "type": "text", "group": "property", "desc": "The land title reference"},
  {"name": "property_rent_per_week", "type": "integer", "group": "property", "desc": "The last advertised rent per week amount"},
  {"name": "property_last_listed_price", "type": "integer", "group": "property", "desc": "Original advertised price of the property if it is on the market"},
  {"name": "property_current_price", "type": "integer", "group": "property", "desc": "Current advertised price of the property if it is on the market"},
  {"name": "property_last_listed_date", "type": "date", "group": "property", "desc": "When the property was last listed on the market"},
  {"name": "property_last_contract_date", "type": "date", "group": "property", "desc": "When the property last went under contract"},
  {"name": "property_last_sold_date", "type": "date", "group": "property", "desc": "When the property last was sold"},
  {"name": "property_last_sold_price", "type": "integer", "group": "property", "desc": "The price the property last sold for"},
  {"name": "property_last_listed_by_agency", "type": "text", "group": "property", "desc": "The agency office that the property was last listed by"},
  {"name": "property_last_listed_by_agent", "type": "text", "group": "property", "desc": "The agent that the property was last listed by"},
  {"name": "property_last_leased_agency", "type": "text", "group": "property", "desc": "The agency office that the property was last leased by"},
  {"name": "property_last_rent_pw", "type": "integer", "group": "property", "desc": "The weekly price the property last leased for"},
  {"name": "property_notes", "type": "text", "group": "property", "desc": "Notes regarding a property"},
  {"name": "property_note_created_date", "type": "date", "group": "property", "desc": "When the notes were created"},
  {"name": "property_note_team_member", "type": "text", "group": "property", "desc": "The creator of the property note. Is can be either the team member's name their Zenu ID"},
  {"name": "task_identifier", "type": "text", "group": "task", "desc": "A unique identifier for the task"},
  {"name": "zenu_task_id", "type": "integer", "group": "task", "desc": "An existing Zenu task ID within your office"},
  {"name": "task_subject", "type": "text", "group": "task", "desc": "The task subject"},
  {"name": "task_notes", "type": "text", "group": "task", "desc": "Notes regarding the task"},
  {"name": "task_status", "type": "text", "group": "task", "desc": "The current status of the task", "accepted": ["Active", "Completed", "Cancelled"]},
  {"name": "task_team_member_1", "type": "text", "group": "task", "desc": "The agent assigned to this task. Can be either the team member's name their Zenu ID"},
  {"name": "task_date_due", "type": "date", "group": "task", "desc": "The date/time that the task is due"},
  {"name": "enquiry_identifier", "type": "text", "group": "enquiry", "desc": "A unique identifier for the enquiry"},
  {"name": "zenu_enquiry_id", "type": "integer", "group": "enquiry", "desc": "An existing Zenu enquiry ID within your office"},
  {"name": "enquiry_notes", "type": "text", "group": "enquiry", "desc": "The text entered by the enquirer"},
  {"name": "enquiry_status", "type": "text", "group": "enquiry", "desc": "The current status of the enquiry", "accepted": ["Active", "Completed"]},
  {"name": "enquiry_source", "type": "text", "group": "enquiry", "desc": "The source of the enquiry"},
  {"name": "enquiry_team_member_1", "type": "text", "group": "enquiry", "desc": "The primary agent of this enquiry. Can be either the team member's name their Zenu ID"},
  {"name": "enquiry_date_created", "type": "date", "group": "enquiry", "desc": "The date of the enquiry"},
  {"name": "inspection_identifier", "type": "date", "group": "inspection", "desc": "A unique identifier for the inspection"},
  {"name": "zenu_inspection_id", "type": "integer", "group": "inspection", "desc": "An existing Zenu inspection ID within your office"},
  {"name": "inspection_notes", "type": "text", "group": "inspection", "desc": "The feedback provided by the inspection attendee"},
  {"name": "inspection_start_date", "type": "date", "group": "inspection", "desc": "The start date & time of the inspection"},
  {"name": "inspection_end_date", "type": "date", "group": "inspection", "desc": "The end date & time of the inspection"},
  {"name": "inspection_is_private", "type": "true/false", "group": "inspection", "desc": "A flag to indicate if this is a private inspection. If left empty, the default value is 'No'", "accepted": ["True", "False"]},
  {"name": "inspection_team_member_1", "type": "text", "group": "inspection", "desc": "The primary agent of this inspection. Can be either the team member's name their Zenu ID"},
  {"name": "inspection_is_interested", "type": "text", "group": "inspection", "desc": "A flag to indicate the interest of the attendee", "accepted": ["Yes", "No", "Maybe"]},
  {"name": "inspection_feedback_price", "type": "integer", "group": "inspection", "desc": "A price provided as feedback by the attendee of the inspection"},
  {"name": "offer_identifier", "type": "text", "group": "offer", "desc": "A unique identifier for the offer"},
  {"name": "zenu_offer_id", "type": "integer", "group": "offer", "desc": "An existing Zenu offer ID within your office"},
  {"name": "offer_price", "type": "date", "group": "offer", "desc": "The offer price"},
  {"name": "offer_terms", "type": "text", "group": "offer", "desc": "The offer terms"},
  {"name": "offer_date", "type": "date", "group": "offer", "desc": "The date that the offer was submitted"},
  {"name": "offer_team_member_1", "type": "text", "group": "offer", "desc": "The primary agent of this offer. Can be either the team member's name their Zenu ID"}
];
